# Generated by Django 5.0 on 2024-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='None', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
